In [637]:
import pandas as pd

df = pd.read_excel(r"D:\Heart_pred\Heart_Disease_Custom_Dataset_600_Rows.xlsx")

In [638]:
df = df.drop_duplicates()
df.columns = df.columns.str.strip().str.lower()

In [639]:
import numpy as np

num_col = df.select_dtypes(include="number").columns

df[num_col] = df[num_col].mask(df[num_col] < 0, np.nan)

In [640]:
cat_col = df.select_dtypes(include=["string", "object", "category"])

for col in cat_col:
    df[col] = df[col].str.strip().str.lower()

In [641]:
from sklearn.model_selection import train_test_split

unnecessary_col = ["patient_id", "heart_disease"]

X = df.drop(unnecessary_col, axis=1)
y = df["heart_disease"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2 , random_state=42)

In [642]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler

In [643]:
numerical_pipeline = Pipeline([
    ("Scaler", MinMaxScaler())
])

categorical_pipeline = Pipeline([
    ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

In [644]:
numeric_col = X_train.select_dtypes(include="number").columns

categorical_col = X_train.select_dtypes(include=["string", "category", "object"]).columns

In [645]:
preprocessor = ColumnTransformer([
    ("num", numerical_pipeline, numeric_col),
    ("cat", categorical_pipeline, categorical_col)
])

In [646]:
from sklearn.linear_model import LogisticRegression

model_LoR = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(random_state=42))
])

In [647]:
model_LoR.fit(X_train, y_train)

y_pred_LoR = model_LoR.predict(X_test)

In [648]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

print("Accuracy :", round(accuracy_score(y_test, y_pred_LoR), 4))
print("Precision :", round(precision_score(y_test, y_pred_LoR), 4))
print("Recall :", round(recall_score(y_test, y_pred_LoR), 4))
print("Confusion Matrix :")
print(confusion_matrix(y_test, y_pred_LoR))
print("Classification Report : ", classification_report(y_test, y_pred_LoR))

Accuracy : 0.9667
Precision : 0.9792
Recall : 0.9792
Confusion Matrix :
[[22  2]
 [ 2 94]]
Classification Report :                precision    recall  f1-score   support

           0       0.92      0.92      0.92        24
           1       0.98      0.98      0.98        96

    accuracy                           0.97       120
   macro avg       0.95      0.95      0.95       120
weighted avg       0.97      0.97      0.97       120



In [649]:
from sklearn.neighbors import KNeighborsClassifier

model_KNN = Pipeline([
    ("preprocessor", preprocessor),
    ("model", KNeighborsClassifier(n_neighbors=5))
])

In [650]:
model_KNN.fit(X_train, y_train)

y_pred_KNN = model_KNN.predict(X_test)

In [651]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, confusion_matrix, f1_score

print("Accuracy Score : ", round(accuracy_score(y_test, y_pred_KNN),4))
print("Precision Score : ", round(precision_score(y_test, y_pred_KNN), 4))
print("Recall Score : ", round(recall_score(y_test, y_pred_KNN), 4))
print("F1 Score : ", f1_score(y_test, y_pred_KNN))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_KNN))
print("Classification Report : ",classification_report(y_test, y_pred_KNN))

Accuracy Score :  0.8083
Precision Score :  0.9101
Recall Score :  0.8438
F1 Score :  0.8756756756756757
Confusion Matrix:
[[16  8]
 [15 81]]
Classification Report :                precision    recall  f1-score   support

           0       0.52      0.67      0.58        24
           1       0.91      0.84      0.88        96

    accuracy                           0.81       120
   macro avg       0.71      0.76      0.73       120
weighted avg       0.83      0.81      0.82       120



In [652]:
from sklearn.tree import DecisionTreeClassifier

model_DT = Pipeline([
    ("preprocessor", preprocessor),
    ("model", DecisionTreeClassifier(random_state=42))
])

In [653]:
model_DT.fit(X_train, y_train)

y_pred_DT = model_DT.predict(X_test)

In [654]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, confusion_matrix, f1_score

print("Accuracy Score : ", round(accuracy_score(y_test, y_pred_DT), 4))
print("Precision Score : ", round(precision_score(y_test, y_pred_DT), 4))
print("Recall Score : ", round(recall_score(y_test, y_pred_DT), 4))
print("F1 Score : ", f1_score(y_test, y_pred_DT))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_DT))
print("Classification Report : ",classification_report(y_test, y_pred_DT))

Accuracy Score :  0.8333
Precision Score :  0.9043
Recall Score :  0.8854
F1 Score :  0.8947368421052632
Confusion Matrix:
[[15  9]
 [11 85]]
Classification Report :                precision    recall  f1-score   support

           0       0.58      0.62      0.60        24
           1       0.90      0.89      0.89        96

    accuracy                           0.83       120
   macro avg       0.74      0.76      0.75       120
weighted avg       0.84      0.83      0.84       120



In [655]:
from sklearn.ensemble import RandomForestClassifier

model_RFC = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestClassifier(n_estimators=100, random_state=42))
])

In [656]:
model_RFC.fit(X_train, y_train)

y_pred_RFC = model_RFC.predict(X_test)

In [657]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, confusion_matrix, f1_score

print("Accuracy Score : ", round(accuracy_score(y_test, y_pred_RFC), 4))
print("Precision Score : ", round(precision_score(y_test, y_pred_RFC), 4))
print("Recall Score : ", round(recall_score(y_test, y_pred_RFC), 4))
print("F1 Score : ", f1_score(y_test, y_pred_RFC))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_RFC))
print("Classification Report : ",classification_report(y_test, y_pred_RFC))

Accuracy Score :  0.9167
Precision Score :  0.9216
Recall Score :  0.9792
F1 Score :  0.9494949494949495
Confusion Matrix:
[[16  8]
 [ 2 94]]
Classification Report :                precision    recall  f1-score   support

           0       0.89      0.67      0.76        24
           1       0.92      0.98      0.95        96

    accuracy                           0.92       120
   macro avg       0.91      0.82      0.86       120
weighted avg       0.92      0.92      0.91       120



In [658]:
from sklearn.svm import SVC

model_SVC = Pipeline([
    ("preprocessor", preprocessor),
    ("model", SVC(random_state=42))
])

In [659]:
model_SVC.fit(X_train, y_train)

y_pred_SVC = model_SVC.predict(X_test)

In [660]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, confusion_matrix, f1_score

print("Accuracy Score : ", round(accuracy_score(y_test, y_pred_SVC), 4))
print("Precision Score : ", round(precision_score(y_test, y_pred_SVC), 4))
print("Recall Score : ", round(recall_score(y_test, y_pred_SVC), 4))
print("F1 Score : ", f1_score(y_test, y_pred_SVC))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_SVC))
print("Classification Report : ",classification_report(y_test, y_pred_SVC))

Accuracy Score :  0.9083
Precision Score :  0.957
Recall Score :  0.9271
F1 Score :  0.9417989417989417
Confusion Matrix:
[[20  4]
 [ 7 89]]
Classification Report :                precision    recall  f1-score   support

           0       0.74      0.83      0.78        24
           1       0.96      0.93      0.94        96

    accuracy                           0.91       120
   macro avg       0.85      0.88      0.86       120
weighted avg       0.91      0.91      0.91       120



In [661]:
from xgboost import XGBClassifier

model_XGB = Pipeline([
    ("preprocessor", preprocessor),
    ("model", XGBClassifier(random_state=42))
])

In [662]:
model_XGB.fit(X_train, y_train)

y_pred_XGB = model_XGB.predict(X_test)

In [663]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, confusion_matrix, f1_score

print("Accuracy Score : ", round(accuracy_score(y_test, y_pred_XGB), 4))
print("Precision Score : ", round(precision_score(y_test, y_pred_XGB), 4))
print("Recall Score : ", round(recall_score(y_test, y_pred_XGB), 4))
print("F1 Score : ", f1_score(y_test, y_pred_XGB))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_XGB))
print("Classification Report : ",classification_report(y_test, y_pred_XGB))

Accuracy Score :  0.9667
Precision Score :  0.9694
Recall Score :  0.9896
F1 Score :  0.979381443298969
Confusion Matrix:
[[21  3]
 [ 1 95]]
Classification Report :                precision    recall  f1-score   support

           0       0.95      0.88      0.91        24
           1       0.97      0.99      0.98        96

    accuracy                           0.97       120
   macro avg       0.96      0.93      0.95       120
weighted avg       0.97      0.97      0.97       120



In [664]:
accuracy_LoR = accuracy_score(y_test, y_pred_LoR)

accuracy_KNN = accuracy_score(y_test, y_pred_KNN)

accuracy_DT = accuracy_score(y_test, y_pred_DT)

accuracy_RFC = accuracy_score(y_test, y_pred_RFC)

accuracy_SVC = accuracy_score(y_test, y_pred_SVC)

accuracy_XGB = accuracy_score(y_test, y_pred_XGB)

In [665]:
import pandas as pd

accuracy_df = pd.DataFrame({
    "Algorithm": [
        "Logistic Regression",
        "KNN",
        "Decision Tree",
        "Random Forest",
        "SVC",
        "XGBoost"
    ],
    "Accuracy": [
        accuracy_LoR,
        accuracy_KNN,
        accuracy_DT,
        accuracy_RFC,
        accuracy_SVC,
        accuracy_XGB
    ]
})

accuracy_df.sort_values(by="Accuracy", ascending=False)

,Algorithm,Accuracy
0,Logistic Regression,0.966667
5,XGBoost,0.966667
3,Random Forest,0.916667
4,SVC,0.908333
2,Decision Tree,0.833333
1,KNN,0.808333


In [666]:
from sklearn.model_selection import cross_val_score

print(cross_val_score(model_LoR, X_train, y_train, cv=5, scoring="accuracy").mean())
print(cross_val_score(model_XGB, X_train, y_train, cv=5, scoring="accuracy").mean())

0.9125
0.90625


In [667]:
print("Final Model Selected: Logistic Regression")

Final Model Selected: Logistic Regression


In [668]:
import joblib

joblib.dump(model_LoR, "heart_disease_final_model.pkl")

['heart_disease_final_model.pkl']